services:
  server1:
    build: 
      context: .
    environment:
      - MODE=Server
      - NAME=server1
    ports:
      - "8081:8080"
    networks:
      - app-network
    # restart: always
    container_name: server1

  server2:
    build:
      context: .
    environment:
      - MODE=Server
      - NAME=server2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: server2

  server3:
    build:
      context: .
    environment:
      - MODE=Server
      - NAME=server3
    ports:
      - "8083:8080"
    networks:
      - app-network
    container_name: server3

  client1:
    build:
      context: .
    environment:
      - MODE=Client
      - NAME=client1
    ports:
      - "8091:8080"
    networks:
      - app-network
    container_name: client1
    stdin_open: true

  client2:
    build:
      context: .
    environment:
      - MODE=Client
      - NAME=client2
    ports:
      - "8092:8080"
    networks:
      - app-network
    container_name: client2
    stdin_open: true

networks:
  app-network:
    name: app-network
    driver: bridge