services:
  server1:
    build: 
      context: .
    environment:
      - MODE=Server
      - NAME=server1
    ports:
      - "8081:8080"
    networks:
      - app-network
    container_name: server1

  server2:
    build:
      context: .
    environment:
      - MODE=Server
      - NAME=server2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: server2

  server3:
    build:
      context: .
    environment:
      - MODE=Server
      - NAME=server3
    ports:
      - "8083:8080"
    networks:
      - app-network
    container_name: server3
  server4:
    build:
      context: .
    environment:
      - MODE=Server
      - NAME=server4
    ports:
      - "8084:8080"
    networks:
      - app-network
    container_name: server4
    # stdin_open: true


networks:
  app-network:
    name: app-network
    driver: bridge