services:
  server1:
    build: 
      context: .
      target: compile-stage
    # image: my-go-app
    environment:
      - MODE=Server
      - NAME=server1
    ports:
      - "8081:8080"
    networks:
      - app-network
    container_name: server1

  server2:
    build:
      context: .
      target: compile-stage
    # image: my-go-app
    environment:
      - MODE=Server
      - NAME=server2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: server2

  client1:
    build:
      context: .
      target: compile-stage
    # image: my-go-app
    environment:
      - MODE=Client
      - NAME=client1
    ports:
      - "8083:8080"
    volumes:
      - ./servers.json:/app/servers.json # Mount JSON config file
    networks:
      - app-network
    container_name: client1

networks:
  app-network:
    name: app-network
    driver: bridge
