services:
  server1:
    image: my-go-app
    environment:
      - MODE=Server
      - NAME=server1
    ports:
      - "8081:8080"
    networks:
      - app-network
    container_name: server1

  server2:
    image: my-go-app
    environment:
      - MODE=Server
      - NAME=server2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: server2

  client1:
    image: my-go-app
    environment:
      - MODE=Client
      - NAME=client1
    volumes:
      - ./servers.json:/app/servers.json # Mount JSON config file
    networks:
      - app-network
    container_name: client1

  client2:
    image: my-go-app
    environment:
      - MODE=Client
      - NAME=client2
    volumes:
      - ./servers.json:/app/servers.json # Mount JSON config file
    networks:
      - app-network
    container_name: client2

networks:
  app-network:
    driver: bridge
