volumes:
  logs:
services:
  server1:
    build: 
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server1
    ports:
      - "8081:8080"
    networks:
      - app-network
    container_name: server1
    volumes:
      - logs:/logs

  server2:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: server2
    volumes:
      - logs:/logs

  server3:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server3
    ports:
      - "8083:8080"
    networks:
      - app-network
    container_name: server3
    volumes:
      - logs:/logs

  server4:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server4
    ports:
      - "8084:8080"
    networks:
      - app-network
    container_name: server4
    volumes:
      - logs:/logs
  server5:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server5
    ports:
      - "8085:8080"
    networks:
      - app-network
    container_name: server5
    volumes:
      - logs:/logs
  server6:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server6
    ports:
      - "8086:8080"
    networks:
      - app-network
    container_name: server6
    volumes:
      - logs:/logs
  server7:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server7
    ports:
      - "8087:8080"
    networks:
      - app-network
    container_name: server7
    volumes:
      - logs:/logs
  server8:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server8
    ports:
      - "8088:8080"
    networks:
      - app-network
    container_name: server8
    volumes:
      - logs:/logs

networks:
  app-network:
    name: app-network
    driver: bridge
