services:
  server1:
    build: 
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=zabServer1
    ports:
      - "8081:8080"
    networks:
      - app-network
    container_name: zabServer1

  server2:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=zabServer2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: zabServer2

  server3:
    build:
      context: ..
      dockerfile: zabFailureTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=zabServer3
    ports:
      - "8083:8080"
    networks:
      - app-network
    container_name: zabServer3

networks:
  app-network:
    name: app-network
    driver: bridge
