services:
  server1:
    build: 
      context: ..
      dockerfile: cxnStressTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server1
    ports:
      - "8081:8080"
    networks:
      - app-network
    container_name: cxnServer1

  server2:
    build:
      context: ..
      dockerfile: cxnStressTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server2
    ports:
      - "8082:8080"
    networks:
      - app-network
    container_name: cxnServer2

  server3:
    build:
      context: ..
      dockerfile: cxnStressTest/Dockerfile
    environment:
      - MODE=Server
      - NAME=server3
    ports:
      - "8083:8080"
    networks:
      - app-network
    container_name: cxnServer3

networks:
  app-network:
    name: app-network
    driver: bridge
